### PR TITLE
Make jQuery an optional dependency.

### PR DESCRIPTION
**Pull request by leighmcculloch**
### What
Make jQuery an optional dependency. https://github.com/robflaherty/jquery-scrolldepth/issues/70

### Why
So that the library can be used on websites without jQuery, but if it is used with jQuery benefits like reliable selectors are used.

### Notes
Each commit is a single atomic change away from jQuery towards plain JavaScript. There are a couple changes that build more compatibility with older browsers.

### CODE REVIEW

**Comment by leighmcculloch** [comment]
So far testing shows it works on IE8 now. TIL that `Array.prototype.indexOf` wasn't in <IE9. I'll keep hunting because this should work all the way back to IE6.

**Comment by robflaherty** [comment]
Thanks so much for the atomic commits and clear descriptions of each change. I have to spend some time on some other projects first but I'll start merging these changes into a dev branch soon.

And don't worry about anything below IE8 :)

Thanks again!

**Comment by leighmcculloch** [comment]
Well, I'm being somewhat selfish, I want it to work on IE 6-7 for a project I'm working on :), but I can submit those changes as a separate PR.

**Comment by leighmcculloch** [comment]
I've rewritten the history of commits, with changes:
1. Pulled out the polyfill for `Element.addEventListener`. The polyfill I'd found in Mozilla's documentation only added support for IE8 and was pretty big and was providing functionality this library isn't using. I was able to replace it with less than half the amount of code which works in IE6 and IE7. Less code and more browser support!
2. Remove some extra `,` on the last element in an Object literal, which causes JavaScript errors on IE6 and IE7.

With these changes the library works all the way back to IE6 as long as you use ID-only selectors for the elements you want to select.

@robflaherty Let me know if there's another branch I can reopen the PR on to make it easier for you to merge straight in. Also feel free to leave any comments for anything I can alter, no matter how minor even if it's style related, so you can merge it straight in.

**Comment by leighmcculloch** [comment]
Mobile support is pretty solid too, working all the way back to iOS 3.2 (the first iPad) and Android 2.2's browser. Unfortunately I couldn't get it to work on iOS 3.0 or Android 1.5, but they have an even more insignificant market share than older IEs so it doesn't matter.

**Comment by leighmcculloch** [comment]
@robflaherty just wanted to touch base if you thought this would be included in the near future?

**Comment by robflaherty** [comment]
@leighmcculloch Hey, sorry I haven't been responsive on this. I've been busy with other work and developing Scroll Depth has become a lower priority but I do still plan to include this. I want to merge in the single-page app options first (#69) since I get a lot of email about that and then will look at the non-jQuery version.

Thanks for being patient. And thanks for putting in so much work on this. It's appreciated!

**Comment by nilssolanki** [comment]
Is this still happening? I would really appreciate this, as we might drop jQuery in future releases as well.

**Comment by robflaherty** [comment]
@nilssolanki It's still on the roadmap. the time i can spend on the project is limited right now and other features have taken priority. but @leighmcculloch put a lot of work into it so i do want to merge it in eventually.

**Comment by leighmcculloch** [comment]
@nilssolanki You can use [my fork](https://github.com/leighmcculloch/gascrolldepth.js) in the meantime if you'd like. Because the changes for non-jQuery were complex I wanted to keep the changes alive while @robflaherty is focusing on other features. The fork is paralleling the main repo and I think is only one change behind.

**Comment by nilssolanki** [comment]
Thank you both very much for the great work!

**Comment by mef** [comment]
@leighmcculloch nice work. Would you mind adding a package.json file in your fork, to enable installation with `npm`? I can send a pull request if needed.

**Pull request closed without merging**
